site_name: Readux Documentation
theme: cinder
repo_url: "https://github.com/readux/"
remote_branch: master
extra_css:
  - "extra/style.css"
pages:
  - Home: 'index.md'
  - Design:
    - 'Design overview': 'design.md'
    - 'Extending readux': 'extending.md'
  - Guides:
    - 'Effective Reagent': 'effective-reagent.md'
    - 'Tutorial': 'tutorial.md'